// client-safe: only question text, answers are typed by the players and kept server-side
export const KNOW_ME_QUESTIONS: string[] = [
  'What is my idea of a perfect date?',
  'Coffee or tea — what am I usually drinking?',
  'What is my comfort movie?',
  'Which song would I play on repeat after a bad day?',
  'Sweet or savory breakfast for me?',
  'What is my biggest fear?',
  'If I could live anywhere, where would it be?',
  'What is my love language?',
  'Beach vacation or mountain cabin — what would I pick?',
  'What is one thing I always complain about?',
  'What was my childhood dream job?',
  'Cats or dogs — which am I?',
  'What is my go-to karaoke song?',
  'Early bird or night owl — me?',
  'What is my most-used emoji?',
  'What gift would make me cry happy tears?',
  'What is my hidden talent?',
  'Which chore do I secretly not mind doing?',
  'What is my favorite way to relax after work?',
  'What nickname do I secretly love being called?',
  'If we won the lottery tomorrow, what would I want to do first?',
  'What is a food I refuse to eat?',
  'What is my favorite photo of us doing?',
  'Rainy day in or adventure out — me?',
  'What is the first thing I notice about people?',
  'What am I most grateful for this year?',
  'What is my dream car (realistically)?',
  'Texting or calling — how do I prefer to talk?',
  'What is my signature dance move situation?',
  'Which of my habits do you find cutest?',
  'What is my favorite season and why?',
  'Pizza topping I always order?',
  'What would I name our future pet?',
  'What is something small that instantly makes my day better?',
  'Do I talk more when happy or when nervous?',
  'What is my guilty-pleasure show?',
  'How do I act when I am hangry?',
  'What is my ideal Sunday plan with you?',
  'What compliment do I fish for the most?',
  'Where was our best kiss so far?',
];
