// SERVER-ONLY: answers must never ship to the client bundle
export type EmojiRiddle = { emojis: string; category: string; answer: string };

export const EMOJI_BANK: EmojiRiddle[] = [
  { emojis: '🍿👑🌊', category: 'Movie', answer: 'titanic' },
  { emojis: '🕷️🧑', category: 'Movie', answer: 'spiderman' },
  { emojis: '🧙‍♂️💍🌋', category: 'Movie', answer: 'lord of the rings' },
  { emojis: '🦁👑🌍', category: 'Movie', answer: 'the lion king' },
  { emojis: '🚗⚡🏁', category: 'Movie', answer: 'cars' },
  { emojis: '🤖🌱🚀', category: 'Movie', answer: 'wall-e' },
  { emojis: '❄️⛄👭', category: 'Movie', answer: 'frozen' },
  { emojis: '🦈🏖️😱', category: 'Movie', answer: 'jaws' },
  { emojis: '👽🏠🍬', category: 'Movie', answer: 'et' },
  { emojis: '🃏🤡🏙️', category: 'Movie', answer: 'joker' },
  { emojis: '🍫🏭🎫', category: 'Movie', answer: 'charlie and the chocolate factory' },
  { emojis: '🧸❤️🚀', category: 'Movie', answer: 'toy story' },
  { emojis: '🌧️💃❤️', category: 'Song', answer: 'dancing in the rain' },
  { emojis: '📞💬👋', category: 'Song', answer: 'call me maybe' },
  { emojis: '💔😢🎤', category: 'Song', answer: 'breakup song' },
  { emojis: '🌙💫🚶‍♀️', category: 'Song', answer: 'walking on moonlight' },
  { emojis: '🔥🚒🚪', category: 'Song', answer: 'burning down the house' },
  { emojis: '👑💃🎸', category: 'Song', answer: 'dancing queen' },
  { emojis: '🌧️💜', category: 'Song', answer: 'purple rain' },
  { emojis: '🍎🖤✨', category: 'Song', answer: 'paint it black' },
  { emojis: '👀👀', category: 'Phrase', answer: 'look look' },
  { emojis: '🐟🌊🚲', category: 'Phrase', answer: 'fish out of water' },
  { emojis: '🌙🧀', category: 'Phrase', answer: 'over the moon' },
  { emojis: '🐝🧢🎬', category: 'Phrase', answer: 'bee movie' },
  { emojis: '🕰️⏳⏰', category: 'Phrase', answer: 'time will tell' },
  { emojis: '🥶🧊❄️💪', category: 'Phrase', answer: 'ice cold' },
  { emojis: '🐷🌧️🛻', category: 'Phrase', answer: 'when pigs fly' },
  { emojis: '🍎📏🌳', category: 'Phrase', answer: 'apple never falls far from the tree' },
  { emojis: '🤫🤐🙊', category: 'Phrase', answer: 'keep it secret' },
  { emojis: '🧠💡✨', category: 'Phrase', answer: 'bright idea' },
  { emojis: '☕😴😵', category: 'Thing', answer: 'monday morning' },
  { emojis: '📱📵😱', category: 'Thing', answer: 'dead phone' },
  { emojis: '🍕🛋️📺🥤', category: 'Thing', answer: 'movie night' },
  { emojis: '🛒💳😭', category: 'Thing', answer: 'shopping spree' },
  { emojis: '🧦🎁🎄', category: 'Thing', answer: 'christmas stocking' },
  { emojis: '🎓🎉😭👩‍🎓', category: 'Thing', answer: 'graduation day' },
  { emojis: '💍👰🤵💐', category: 'Thing', answer: 'wedding day' },
  { emojis: '🌅☕🥐', category: 'Thing', answer: 'sunrise breakfast' },
  { emojis: '🏖️🌞🕶️🍹', category: 'Thing', answer: 'beach vacation' },
  { emojis: '🏠💰🔑📝', category: 'Thing', answer: 'buying a house' },
];
