export type QuizQuestion = { q: string; options: string[]; correct: number };

// SERVER-ONLY: correct answers must never ship to the client bundle
export const QUIZ_BANK: QuizQuestion[] = [
  { q: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Mercury'], correct: 1 },
  { q: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], correct: 2 },
  { q: 'How many continents are there?', options: ['5', '6', '7', '8'], correct: 2 },
  { q: 'Which animal is the fastest land animal?', options: ['Lion', 'Cheetah', 'Gazelle', 'Horse'], correct: 1 },
  { q: 'What gas do plants absorb from the air?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correct: 2 },
  { q: 'Which country invented tea?', options: ['India', 'China', 'Japan', 'England'], correct: 1 },
  { q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Seoul'], correct: 2 },
  { q: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correct: 2 },
  { q: 'Which is the smallest planet in our solar system?', options: ['Mars', 'Mercury', 'Pluto', 'Venus'], correct: 1 },
  { q: 'What does "www" stand for?', options: ['World Wide Web', 'Wide World Web', 'Web World Wide', 'Wired Web World'], correct: 0 },
  { q: 'Which bird cannot fly?', options: ['Eagle', 'Penguin', 'Sparrow', 'Parrot'], correct: 1 },
  { q: 'What is the hardest natural substance?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correct: 2 },
  { q: 'How many minutes are in a full day?', options: ['1200', '1440', '1600', '2400'], correct: 1 },
  { q: 'Which language has the most native speakers?', options: ['English', 'Hindi', 'Spanish', 'Mandarin Chinese'], correct: 3 },
  { q: 'What is a baby cat called?', options: ['Cub', 'Kitten', 'Puppy', 'Calf'], correct: 1 },
  { q: 'Which fruit has its seeds on the outside?', options: ['Apple', 'Strawberry', 'Banana', 'Grape'], correct: 1 },
  { q: 'What color do you get mixing blue and yellow?', options: ['Green', 'Purple', 'Orange', 'Brown'], correct: 0 },
  { q: 'Mount Everest lies between Nepal and which country?', options: ['India', 'China', 'Bhutan', 'Pakistan'], correct: 1 },
  { q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correct: 1 },
  { q: 'Which sea creature has eight arms?', options: ['Squid', 'Octopus', 'Starfish', 'Jellyfish'], correct: 1 },
  { q: 'What is the main ingredient in guacamole?', options: ['Peas', 'Avocado', 'Cucumber', 'Zucchini'], correct: 1 },
  { q: 'Which sport uses a shuttlecock?', options: ['Tennis', 'Badminton', 'Squash', 'Ping pong'], correct: 1 },
  { q: 'The Great Barrier Reef is off the coast of which country?', options: ['Brazil', 'Australia', 'Mexico', 'Thailand'], correct: 1 },
  { q: 'How many bones does an adult human have?', options: ['186', '206', '226', '246'], correct: 1 },
  { q: 'What is the tallest animal in the world?', options: ['Elephant', 'Giraffe', 'Ostrich', 'Moose'], correct: 1 },
  { q: 'Which metal is liquid at room temperature?', options: ['Mercury', 'Lead', 'Tin', 'Zinc'], correct: 0 },
  { q: 'What does a "nocturnal" animal do at night?', options: ['Sleeps', 'Is active', 'Migrates', 'Hibernates'], correct: 1 },
  { q: 'Which instrument has 88 keys?', options: ['Organ', 'Accordion', 'Piano', 'Harpsichord'], correct: 2 },
  { q: 'What is the currency of the United Kingdom?', options: ['Euro', 'Dollar', 'Pound', 'Franc'], correct: 2 },
  { q: 'Honey never spoils — what is it made mostly of?', options: ['Water', 'Sugar', 'Pollen', 'Wax'], correct: 1 },
  { q: 'Which is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correct: 1 },
  { q: 'How many players are on a soccer team on the field?', options: ['9', '10', '11', '12'], correct: 2 },
  { q: 'What do bees collect to make honey?', options: ['Pollen only', 'Nectar', 'Sap', 'Dew'], correct: 1 },
  { q: 'Which planet has the most rings?', options: ['Saturn', 'Uranus', 'Neptune', 'Jupiter'], correct: 0 },
  { q: 'What is the freezing point of water in Fahrenheit?', options: ['0°F', '16°F', '32°F', '48°F'], correct: 2 },
  { q: 'Which country gifted the Statue of Liberty to the USA?', options: ['Britain', 'France', 'Spain', 'Italy'], correct: 1 },
  { q: 'What is a group of lions called?', options: ['Pack', 'Herd', 'Pride', 'Flock'], correct: 2 },
  { q: 'Which fruit is famous for keeping doctors away?', options: ['Banana', 'Orange', 'Apple', 'Cherry'], correct: 2 },
  { q: 'How many colors are in a rainbow?', options: ['5', '6', '7', '9'], correct: 2 },
  { q: 'What is the smallest unit of life?', options: ['Atom', 'Cell', 'Molecule', 'Organ'], correct: 1 },
  { q: 'Which dance originated in Argentina?', options: ['Salsa', 'Tango', 'Waltz', 'Flamenco'], correct: 1 },
  { q: 'What does "GPS" stand for?', options: ['Global Positioning System', 'General Position Service', 'Geo Path System', 'Global Path Signal'], correct: 0 },
  { q: 'Which is the only mammal that can truly fly?', options: ['Flying squirrel', 'Bat', 'Colugo', 'Sugar glider'], correct: 1 },
  { q: 'What is the capital of Italy?', options: ['Milan', 'Venice', 'Rome', 'Naples'], correct: 2 },
  { q: 'Sunsets look red because of what effect?', options: ['Reflection', 'Atmosphere scattering', 'Refraction', 'Diffraction'], correct: 1 },
  { q: 'Which shape has no sides?', options: ['Triangle', 'Square', 'Circle', 'Pentagon'], correct: 2 },
  { q: 'What is 15% of 200?', options: ['15', '20', '30', '45'], correct: 2 },
  { q: 'Which animal says "moo"?', options: ['Goat', 'Cow', 'Sheep', 'Duck'], correct: 1 },
  { q: 'Where do penguins live naturally?', options: ['Arctic', 'Antarctica', 'Alps', 'Siberia'], correct: 1 },
  { q: 'What is the most consumed drink in the world after water?', options: ['Coffee', 'Tea', 'Soda', 'Milk'], correct: 1 },
  { q: 'How many days in a leap year?', options: ['364', '365', '366', '367'], correct: 2 },
  { q: 'Which body part pumps blood?', options: ['Lungs', 'Brain', 'Heart', 'Liver'], correct: 2 },
  { q: 'What language is spoken in Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Italian'], correct: 1 },
  { q: 'Which is the fastest sea animal?', options: ['Dolphin', 'Sailfish', 'Shark', 'Tuna'], correct: 1 },
  { q: 'What do caterpillars turn into?', options: ['Beetles', 'Butterflies', 'Bees', 'Flies'], correct: 1 },
  { q: 'Which is the largest desert?', options: ['Sahara', 'Antarctic Desert', 'Gobi', 'Arabian'], correct: 1 },
  { q: 'What does "DIY" stand for?', options: ['Do It Yourself', 'Do It Your way', 'Done In Years', 'Design It Yourself'], correct: 0 },
  { q: 'Which star is closest to Earth?', options: ['Sirius', 'The Sun', 'Polaris', 'Alpha Centauri'], correct: 1 },
  { q: 'How many wheels does a tricycle have?', options: ['2', '3', '4', '5'], correct: 1 },
  { q: 'Which fruit is yellow and curved?', options: ['Apple', 'Banana', 'Mango', 'Pear'], correct: 1 },
];
